name: Publish container images
on:
  release:
    types:
    - released
jobs:
  push_to_registry:
    name: Push container images
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v2
    - name: Setup Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.15
    - name: Install ko
      run: |
        cd $(mktemp -d)
        go get github.com/google/ko/cmd/ko@v0.6.2-0.20201109152754-715c03ebc2b1
      env:
        GO111MODULE: on
    - name: Build and push container images
      run: |
        ko auth login docker.pkg.github.com -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
        ko publish --base-import-paths --platform all --tags latest,${{ github.ref }} .
      env:
        KO_DOCKER_REPO: docker.pkg.github.com/${{ github.repository }}
