name: Release
on:
  push:
    tags:
    - 'v*'
  #   branches:
  #   - main
  # pull_request:
  #   branches:
  #   - main
jobs:
  build:
    name: Release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.15
    - name: Build binaries
      run: |
        GOOS=darwin GOARCH=amd64 go build -o ghr-test_darwin_amd64 .
        GOOS=linux GOARCH=amd64 go build -o ghr-test_linux_amd64 .
        GOOS=linux GOARCH=arm64 go build -o ghr-test_linux_arm64 .
    - name: Create checksums
      run: shasum -a 256 ghr-test_* > SHA256SUMS
    - name: Install ko
      run: |
        cd $(mktemp -d)
        go get github.com/google/ko/cmd/ko@v0.6.2-0.20201109152754-715c03ebc2b1
      env:
        GO111MODULE: on
    - name: Build and push container images
      run: |
        echo -n 'image_digest=' >> $GITHUB_ENV
        ko auth login docker.pkg.github.com -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
        ko publish --base-import-paths --platform all . >> $GITHUB_ENV
      env:
        KO_DOCKER_REPO: docker.pkg.github.com/${{ github.repository }}
    - name: Create release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: ${{ github.ref }}
        body: |
          docker.pkg.github.com/${{ github.repository }}/${{ github.event.repository.name }}:${GITHUB_REF##*/}
          $image_digest
    - name: Upload asset darwin amd64
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ghr-test_darwin_amd64
        asset_name: ghr-test_darwin_amd64
        asset_content_type: application/octet-stream
    - name: Upload binary linux amd64
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ghr-test_linux_amd64
        asset_name: ghr-test_linux_amd64
        asset_content_type: application/octet-stream
    - name: Upload binary linux arm64
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ghr-test_linux_arm64
        asset_name: ghr-test_linux_arm64
        asset_content_type: application/octet-stream
    - name: Upload checksum file
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: SHA256SUMS
        asset_name: SHA256SUMS
        asset_content_type: text/plain
