name: Release
on:
  push:
    tags:
      - 'v*'
  #   branches:
  #   - main
  # pull_request:
  #   branches:
  #   - main
jobs:
  build:
    name: Release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.15
    - name: Build binaries
      run: |
        for GOOS in darwin linux ; do
          for GOARCH in amd64 arm64 ; do
            go build -o ghr-test_${GOOS}_${GOARCH} .
          done
        done
    - name: Create checksums
      run: shasum -a 256 ghr-test_* > SHA256SUMS
    - name: Create release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: ${{ github.ref }}
    - name: Upload asset darwin amd64
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ghr-test_darwin_amd64
        asset_name: ghr-test_darwin_amd64
        asset_content_type: application/octet-stream
    - name: Upload binary darwin arm64
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ghr-test_darwin_arm64
        asset_name: ghr-test_darwin_arm64
        asset_content_type: application/octet-stream
    - name: Upload binary linux amd64
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ghr-test_linux_amd64
        asset_name: ghr-test_linux_amd64
        asset_content_type: application/octet-stream
    - name: Upload binary linux arm64
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ghr-test_linux_arm64
        asset_name: ghr-test_linux_arm64
        asset_content_type: application/octet-stream
    - name: Upload checksum file
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: SHA256SUMS
        asset_name: SHA256SUMS
        asset_content_type: text/plain
